Repository Vishwajith-Shettigar/NextGen, pull requests merged in 2024-10, with the labels that each got.

#51 Highlight create here text in login activity and sign in here text in sign up activity
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: good first issue, hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#56 Improved UI for Sign in & Sign up Screen
  app/src/main/res/drawable/bg_edt.xml
  app/src/main/res/drawable/btn_color.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#53 refactor: format code spacing
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nextgen/Activity/ActivityScope.kt
  app/src/main/java/com/example/nextgen/Fragment/FragmentComponent.kt
  app/src/main/java/com/example/nextgen/editprofile/EditProfileViewModel.kt
  app/src/main/java/com/example/nextgen/message/MessageFragment.kt
  app/src/main/java/com/example/nextgen/message/MessageListViewModelFactory.kt
  app/src/main/java/com/example/nextgen/message/MessageViewModel.kt
  app/src/main/java/com/example/nextgen/privacy/OnPrivacyItemClicked.kt
  app/src/main/java/com/example/nextgen/privacy/PrivacyItemsViewModel.kt
  app/src/main/java/com/example/nextgen/privacy/PrivacyViewModel.kt
  app/src/main/java/com/example/nextgen/profile/ProfileViewModel.kt
  app/src/main/java/com/example/nextgen/service/VideoCallService.kt
  app/src/main/java/com/example/nextgen/signup/RouteToSignupSigninActivityListener.kt
  app/src/main/java/com/example/nextgen/signup/SignupSigninActivity.kt
  app/src/main/java/com/example/nextgen/videocall/VideoCallActivity.kt
  app/src/main/java/com/example/nextgen/viewprofile/ViewProfileActivity.kt
  app/src/main/java/com/example/nextgen/viewprofile/ViewProfileViewModel.kt
  app/src/main/java/com/example/nextgen/webrtc/MessageModel.kt
  app/src/main/java/com/example/nextgen/webrtc/PeerConnectionObserver.kt
  app/src/main/java/com/example/nextgen/webrtc/WebSocketManager.kt
  data/src/main/java/com/example/data/dao/UserDao.kt
  data/src/main/java/com/example/data/repository/userRepo.kt
  domain/src/main/java/com/example/domain/nearby/NearByController.kt
  domain/src/main/java/com/example/utility/Constants.kt
  domain/src/main/java/com/example/utility/Result.kt
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#69 Create Code_of_Conduct.md
  Code_of_Conduct.md
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#72 fix dark theme for signIn and signUp screen
  app/src/main/res/drawable/bg_edt.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#71 Added splash Screen
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nextgen/Activity/ActivityComponent.kt
  app/src/main/java/com/example/nextgen/signup/SignupSigninActivity.kt
  app/src/main/java/com/example/nextgen/splashScreen/SplashScreenActivity.kt
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#78 Added eye icon to password field
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#84 Change Notification Fragment layout from linear to Constraint
  app/src/main/res/layout/fragment_notification.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#90 Migrating the Privacy Fragment to constraint layout
  app/src/main/res/layout/activity_privacy.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#91 Migrate near_by_fragment to constraint layout
  app/src/main/res/layout/fragment_near_by.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#88 Ask the user to enable location when the device's location is off
  app/src/main/java/com/example/nextgen/nearby/NearByFragment.kt
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#95 migrate signup fragment to constraint layout
  app/src/main/res/layout/fragment_signup.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#96 Migrating the Profile Fragment UI to Constraint layout
  app/src/main/java/com/example/nextgen/profile/Activity_profile.kt
  app/src/main/res/layout/activity_profile.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#102 Updating the Video Call Fragment UI to Constraint Layout
  app/src/main/res/drawable/ic_baseline_videocam_24.xml
  app/src/main/res/layout/activity_video_call.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#104 Animated splashscreen
  .idea/gradle.xml
  .idea/misc.xml
  activity_splash_screen.xml
  app/build.gradle
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/font/itali.ttf
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/raw/logo.json
  raw/logo.json
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#108 Fixed Keyboard Dismissal Issue on Signup/SignIn Screen
  app/src/main/java/com/example/nextgen/signup/SignInFragment.kt
  app/src/main/java/com/example/nextgen/signup/SignupFragment.kt
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#89 Enhanced README with Troubleshooting Section.
  README.md
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#110 Fixed Profile Image Fitting Issue in Navigation Drawer
  app/src/main/res/layout/fragment_profile.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#115 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#116 added greeting.yml
  .github/workflow/greetings.yaml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#124 Enhanced the Privacy Screen and its Dialogs
  app/src/main/java/com/example/nextgen/privacy/PrivacyFragment.kt
  app/src/main/res/drawable/background_dialog.xml
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/layout/dialog_yes_no_options.xml
  app/src/main/res/layout/fragment_privacy.xml
  app/src/main/res/values/themes.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#128 Converted Edit Profile Layout to Constraint Layout
  app/src/main/res/layout/fragment_edit_profile.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#127 migrate profile fragment to constraint layout
  app/src/main/res/layout/fragment_profile.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#129 Converting Splash layout to constraint layout
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/values/strings.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#131 Converted Yes-No-Dialog-Layout to Constraint Layout
  app/src/main/res/layout/dialog_yes_no_options.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#138 Sender msg migration to constraint view
  app/src/main/res/layout/sender_message_layout.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#136 migration of privacy-items-layout to constraint layout
  app/src/main/res/layout/privacy_items_layout.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#137 Receiver msg migration to constraint layout
  app/src/main/res/layout/receiver_message_layout.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#135 Nearby profile layout to constraint layout
  app/src/main/res/layout/nearby_profile_dialog.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#134 Privacy fragment migration to constraint layout
  app/src/main/res/layout/fragment_privacy.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 2, hacktoberfest-accepted

#139 Labeler workflow
  .github/workflows/auto-label.yml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted

#133 Changed user circle color to blue with low opacity.
  app/src/main/java/com/example/nextgen/nearby/NearByFragment.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: hacktoberfest, gssoc, gssoc-ext, level 1, hacktoberfest-accepted
